# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

# config/packages/fos_ck_editor.yaml
# fos_ck_editor:
#     base_path: "bundles/ckeditor"
#     js_path:   "bundles/ckeditor/ckeditor.js"
#     configs:
#         main_config: 
#             toolbar: standard
