vich_uploader:
    db_driver: orm # Doctrine ORM
    mappings:
        image_upload:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'