vich_uploader:
    db_driver: orm # Doctrine ORM

    metadata:
      type: attribute

    mappings:
      image_user_upload:
        uri_prefix: /public/images
        upload_destination: '%kernel.project_dir%/public/images/user'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true